config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  # Rotas para login/logout
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :comments

  resources :users do
    resources :articles
    collection do
      get :admin
    end
    member do
      get :edit_user_type #mesmo nome que tem no controller
      patch :update_user_type #é o mesmo nome chamado no controlador
    end
  end
  
  resources :articles do
    resources :comments
  end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /comments or /comments.json
  def index
    @article = Article.find(params[:article_id])
    @comments = @article.comments.order(created_at: :asc)
  end

  # GET /comments/1 or /comments/1.json
  def show  
    @user = current_user
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  # GET /comments/new
  def new
    @user = current_user
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build

  end

  # GET /comments/1/edit
  def edit
    @article = Article.find(params[:article_id])
  
  end

  # POST /comments or /comments.json
  def create
    @user = current_user
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = @user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to  article_path(@article), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
  
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to article_path(@article), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!
    respond_to do |format|
      format.html { redirect_to article_path(@article), status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.expect(comment: [ :name, :comment ])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Name:</strong>
    <%= comment.name %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.comment %>
  </p>
  <p>
    <strong>Created at</strong>
    <%= dateBR(comment.created_at) %>
  <p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model:  [@article, @comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= form.hidden_field :name, value: current_user.name %>
  

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.textarea :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", article_comment_path(@comment.article, @comment) %> |
  <%= link_to "Back to comments", article_comments_path(@comment.article) %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <hr>
    <%= render comment %>
    <p>
      <%if can? :destroy, comment%>
        <%= button_to "Apagar esse comentário",article_comment_path(comment.article, comment), method: :delete %>
      <%end%>
    </p>
    <p>
      <% if can? :edit, comment %>
        <%= link_to "Show this comment",article_comment_path(comment.article, comment) %>
      <%end%>
    </p>
  <% end %>
</div>

<% if can? :create, Comment %>
  <%= link_to "New comment", new_article_comment_path() %>
<% end %>

<%= link_to "Back to Article",article_path(@article) %>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments",article_path(@article) %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <% if can? :edit, Comment %>
    <%= link_to "Edit this comment", edit_article_comment_path(@comment.article, @comment) %> |
    <%= button_to "Destroy this comment", article_comment_path(@comment.article, @comment), method: :delete %>
  <% end %>
  
  <%= link_to "Voltar para o artigo", article_path(@article) %>

</div>