config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  # Rotas para login/logout
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :comments

  resources :users do
    resources :articles
    collection do
      get :admin
    end
    member do
      get :edit_user_type #mesmo nome que tem no controller
      patch :update_user_type #é o mesmo nome chamado no controlador
    end
  end
  
  resources :articles do
    resources :comments
  end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # enum user_type: {commenter: 0, author: 1, admin: 2}
  has_secure_password
  validate :strong_password, if: :password_required?
  validates :password, confirmation: true # Valida a confirmação da senha
  validates :password_confirmation, presence: true, if: :password_digest_changed?
  has_many :comments,dependent: :destroy
  has_many :articles, foreign_key: :user_id, dependent: :destroy

  def self.email_in_use?(email)
    where(email: email.downcase).exists?
  end

  def self.strong_password?(password)
    return false if password.length < 12
    return false unless password.match?(/[a-z]/)
    return false unless password.match?(/[A-Z]/)
    return false unless password.match?(/[^a-zA-Z0-9]/)

    true
  end

  private
  #para saber se tem senha ou não e poder usar meu formulário
  #Nao deixa o strong_password ser chamado
  def password_required?
    password.present? || new_record?
  end

  def strong_password
    unless self.class.strong_password?(password)
      errors.add(:password, "Deve ter pelo menos 12 caracteres, incluindo uma letra maiúscula, uma minúscula e um caractere especial.")
    end
    # validates :email, presence: true, uniqueness: { case_sensitive: false }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy edit_user_type update_user_type ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  def admin
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    if User.email_in_use?(user_params[:email])
      redirect_to new_user_path, alert: "Este email já está sendo utilizado."
    else
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html { redirect_to login_path, notice: "Usuário cadastrado com sucesso, faça login" }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  # PATCH/PUT /users/1 or /users/1.json
  def update
    if User.email_in_use?(user_params[:email])
      redirect_to new_user_path, alert: "Este email já está sendo utilizado."
    else
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end # Fecha o else
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to admin_users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET
  def edit_user_type
    @user = User.find(params[:id])
    render "users/edit_user_type"
  end

  # PATCH/PUT /users/:id/update_user_type
  def update_user_type
    if @user.update(user_type_params)
      redirect_to admin_users_path, notice: "Tipo de usuário atualizado com sucesso."
    else
      render :edit_user_type, status: :unprocessable_entity
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_type, :name, :email, :password,  :password_confirmation)
    end

    #Para a função de editar o tipo de usuário
    def user_type_params
      params.require(:user).permit(:user_type)
    end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_type, value: 1 %>
  
  
  <% if can? :manage, :all%>
     <div>
      <%= form.label :user_type, style: "display: block" %>
      <%= form.text_field :user_type %>
    </div>
    
  <%end%>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "Confirmação de Senha" %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>User type:</strong>
    <%= user.user_type %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  
  

  

</div>

app/views/users/admin.html.erb
<h1>View de Admim</h1>
<p>Aqui você pode mudar o tipo dos outros usuários</p>
<div id="users">
  <%= link_to "Voltar para articles", Article,style: "display: block; margin-bottom: 5px;" %>  
  <% @users.each do |user| %>
    <div>
      <%= user.name %> (<%= user.email %>)
      <%= link_to "Editar usuário", edit_user_path(user) %> |
      <%= link_to "Editar usuário2", edit_user_type_user_path(user) %> |
      <%= button_to "Destruir esse usuário", user, method: :delete%>
    </div>
    <hr>
  <% end %>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", admin_users_path, method: :get %>
</div>

app/views/users/edit_user_type.html.erb
<h1>Alterar Tipo de Usuário</h1>

<%= form_with(model: @user, url: update_user_type_user_path(@user), method: :patch) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red;">
      <h2><%= pluralize(@user.errors.count, "erro") %> impediram a atualização:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_type, "Tipo de Usuário", style: "display: block;" %>
    <%= form.select :user_type, options_for_select({"Visitante" => 1, "Autor" => 2, "Admin" => 3}, @user.user_type), prompt: 'Selecione o tipo de usuário' %>
  </div>

  <div style="margin-top: 15px;">
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Voltar", admin_users_path, class: "btn btn-secondary", style: "margin-top: 15px;" %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>
<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<% if @user.errors.any? %>
  <div>
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>Cadastro de usuário</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <h1>Esses são os articles desse usuário</h1>

  <ul>
    <% @articles.each do |article| %>
      <li>
        <h2><%= link_to article.title, article_path(article) %></h2>
        <p><%= truncate(article.body, length: 100) %></p>
        <p><small>Published on: <%= article.created_at.strftime("%d %b %Y") %></small></p>
      </li>
    <% end %>
  </ul>

  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users",  admin_users_path, method: :get %>
  <%= link_to "Create Article", new_user_article_path(@user) %>
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>